# Generated by Django 6.0.2 on 2026-03-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='current_slide',
            field=models.IntegerField(default=0),
        ),
    ]
