# Generated by Django 6.0.2 on 2026-03-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_topicprogress_current_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicprogress',
            name='current_slide',
        ),
        migrations.RemoveField(
            model_name='topicprogress',
            name='updated_at',
        ),
    ]
