# Generated by Django 6.0.2 on 2026-03-05 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_slidecompletion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicprogress',
            old_name='progress_percent',
            new_name='slides_completed',
        ),
    ]
