# Generated by Django 6.0.2 on 2026-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_progress_percent_topicprogress_slides_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
