# Generated by Django 6.0.2 on 2026-03-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_option_a_question_option_a_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_a_en',
            new_name='option_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_b_en',
            new_name='option_b',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_c_en',
            new_name='option_c',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_d_en',
            new_name='option_d',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text_en',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_a_de',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_a_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_a_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b_de',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c_de',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d_de',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text_de',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text_fr',
        ),
    ]
