# Generated by Django 6.0.2 on 2026-04-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
