# Generated by Django 6.0.2 on 2026-04-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='last_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
