# Generated by Django 6.0.2 on 2026-04-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_usersettings_last_sent_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="last_sent_date",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="last_sent_reminder_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
