# Generated by Django 6.0.2 on 2026-04-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_remove_usersettings_last_sent_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="category",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("subject", "slug", "level")},
        ),
    ]
