# Generated by Django 6.0.2 on 2026-04-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("subject", "slug")},
        ),
        migrations.RemoveField(
            model_name="category",
            name="level",
        ),
    ]
