# Generated by Django 6.0.2 on 2026-04-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="category",
            name="discipline",
            field=models.CharField(
                blank=True,
                choices=[
                    ("physics", "Physics"),
                    ("chemistry", "Chemistry"),
                    ("biology", "Biology"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("subject", "slug", "level")},
        ),
    ]
