# Generated by Django 6.0.2 on 2026-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
    ]
