# Generated by Django 6.0.2 on 2026-04-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_emailverification_attempts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
